# Generated by Django 4.1.5 on 2023-07-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookiestand',
            old_name='owner',
            new_name='reviewer',
        ),
    ]
