# Generated by Django 4.1.5 on 2023-07-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0002_rename_owner_cookiestand_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookiestand',
            old_name='location',
            new_name='name',
        ),
    ]
