# Generated by Django 4.1.5 on 2023-07-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0003_rename_location_cookiestand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiestand',
            name='raiting',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
