# Generated by Django 4.1.5 on 2023-07-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0004_cookiestand_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiestand',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
